// When the button is clicked, navigate to another HTML page or do other actions
    document.getElementById('submit-button').addEventListener('click', function() {
        const selectedYear = yearDropdown.value;
        const selectedMake = document.getElementById('make').value;
        const selectedModel = document.getElementById('model').value;
        
        if (selectedYear && selectedMake && selectedModel) {
            // Implement logic to navigate to another HTML page, or populate Youtube and eBay sections
            alert(`You've selected a ${selectedYear} ${selectedMake} ${selectedModel}`);
        } else {
            alert('Please select all fields');
        }
    });



    // Populate the "Year" dropdown dynamically
    const yearDropdown = document.getElementById('year');
    const currentYear = new Date().getFullYear();
    for (let year = 1985; year <= currentYear; year++) {
        const option = document.createElement('option');
        option.value = year;
        option.innerText = year;
        yearDropdown.appendChild(option);
    }

    // Start adding data here.....
    const carData = {

        1985: {
            'BMW': [ '3-Series',  '7-Series', '6-Series', ],
            'Chrysler': ['Executive', 'Fifth Avenue', 'Laser', 'LeBaron', 'New Yorker', ],
            'Acrua': [ 'Intergra', 'Legend',  ],
            'Cadillac': ['Cimarron', 'DeVille', 'Eldorado', 'Fleetwood', 'Seville', ],
            'Honda': ['Accord', 'CRX', 'Civic', 'Prelude', ],
            'Jeep': ['CJ-8', 'J-Series' ],
            'Mazda': ['626', 'B-Series', 'GLC', 'RX7' ],
            'Dodge': ['600', 'Aries', 'B-Series', 'Caravan', 'Charger', 'Colt', 'Conquest', 'D150', 'Daytona', 'Diplomat', 'Lancer', 'Mini Ram Van', 'Omni', 'Ram 50', 'Ramcharger'],
            'GMC': [ 'Jimmy', 'Savana', 'Sierra', 'Suburban', ],
            'Ford': ['Bronco', 'EXP', 'Excort', 'F-Series', 'LTD', 'Mustang', 'Tempo', 'Thunderbird',  'Probe', ],
            'Toyota': ['4Runner', 'Supra', 'Mr-2', 'Previa', 'T100', 'Camry', 'Corolla', 'Land Cruiser',  ],
        },
        1986: {
            'BMW': [ '3-Series',  '7-Series', '6-Series', ],
            'Hyundai': ['Excel', ],
            'Chrysler': ['Executive', 'Fifth Avenue', 'LeBaron', 'New Yorker', ],
            'Acrua': [ 'Intergra', 'Legend',  ],
            'Cadillac': ['Cimarron', 'DeVille', 'Eldorado', 'Fleetwood', 'Seville', ],
            'Honda': ['Accord', 'CRX', 'Civic', 'Prelude', ],
            'Jeep': ['Comanche', 'J-Series' ],
            'Mazda': ['323', '626', 'B-Series', 'RX7' ],
            'Dodge': ['600', 'Aries', 'B-Series', 'Caravan', 'Charger', 'Colt', 'Conquest', 'D150', 'Daytona', 'Diplomat', 'Lancer', 'Mini Ram Van', 'Omni', 'Ram 50', 'Ramcharger'],
            'GMC': [ 'Jimmy', 'Savana', 'Sierra', 'Suburban', ],
            'Ford': ['Bronco', 'EXP', 'Excort', 'F-Series', 'LTD', 'Mustang', 'Tempo', 'Thunderbird',  'Probe', 'Ranger', 'Taurus', ],
            'Toyota': ['4Runner', 'Supra', 'Mr-2', 'Previa', 'T100', 'Camry', 'Corolla', 'Land Cruiser',  ],
        },
        1987: {
            'BMW': [ '3-Series',  '7-Series', '6-Series', ],
            'Hyundai': ['Excel', ],
            'Chrysler': ['Conquest', 'Fifth Avenue', 'LeBaron', 'New Yorker', ],
            'Acrua': [ 'Intergra', 'Legend',  ],
            'Cadillac': ['Allante', 'Brougham', 'DeVille', 'Eldorado', 'Fleetwood', 'Seville', ],
            'Honda': ['Accord', 'CRX', 'Civic', 'Prelude', ],
            'Jeep': ['Comanche', 'J-Series' ],
            'Mazda': ['323', '626', 'B-Series', 'RX7' ],
            'Dodge': ['600', 'Aries', 'B-Series', 'Caravan', 'Charger', 'Colt', 'D150','Dakota', 'Daytona', 'Diplomat', 'Lancer', 'Mini Ram Van', 'Omni','Raider','Ram 50', 'Ramcharger', 'Shadow'],
            'GMC': [ 'Jimmy', 'Savana', 'Sierra', 'Suburban', ],
            'Ford': ['Bronco', 'EXP', 'Excort', 'F-Series', 'LTD', 'Mustang', 'Tempo', 'Thunderbird',  'Probe', 'Ranger', 'Taurus', ],
            'Toyota': ['4Runner', 'Supra', 'Mr-2', 'Previa', 'T100', 'Camry', 'Corolla', 'Land Cruiser',  ],
        },
        1988: {
            'BMW': [ '3-Series',  '7-Series', '6-Series', 'Z1'],
            'Hyundai': ['Excel', ],
            'Chrysler': ['Conquest', 'Fifth Avenue', 'LeBaron', 'New Yorker', ],
            'Acrua': [ 'Intergra', 'Legend',  ],
            'Cadillac': ['Allante', 'Brougham', 'DeVille', 'Eldorado', 'Fleetwood', 'Seville', ],
            'Honda': ['Accord', 'CRX', 'Civic', 'Prelude', ],
            'Jeep': ['Comanche'],
            'Mazda': ['323', '626', 'B-Series', 'MPV', 'MX', 'RX7' ],
            'Dodge': ['600', 'Aries', 'B-Series', 'Caravan', 'Colt', 'D150','Dakota', 'Daytona', 'Diplomat', 'Dynasty', 'Lancer', 'Mini Ram Van', 'Omni','Raider','Ram 50', 'Ramcharger', 'Shadow'],
            'GMC': [ 'Jimmy', 'Savana', 'Sierra', 'Suburban', ],
            'Ford': ['Bronco', 'EXP', 'Excort', 'F-Series', 'LTD', 'Mustang', 'Tempo', 'Thunderbird',  'Probe', 'Ranger', 'Taurus', 'Aerostar' ],
            'Toyota': ['4Runner', 'Supra', 'Mr-2', 'Previa', 'T100', 'Camry', 'Corolla', 'Land Cruiser', ],
        },
        1989: {
            'BMW': [ '3-Series',  '7-Series', '6-Series', 'Z1'],
            'Hyundai': ['Excel', 'Scoupe', 'Sonata', ],
            'Chrysler': ['Conquest', 'Fifth Avenue', 'LeBaron', 'TC', 'New Yorker', ],
            'Acrua': [ 'Intergra', 'Legend',  ],
            'Cadillac': ['Allante', 'Brougham', 'DeVille', 'Eldorado', 'Fleetwood', 'Seville', ],
            'Honda': ['Accord', 'CRX', 'Civic', 'Prelude', ],
            'Jeep': ['Comanche'],
            'Mazda': ['323', '626', '929', 'B-Series', 'MPV', 'MX', 'Miata', 'RX7' ],
            'Dodge': ['Aries', 'B-Series', 'Caravan', 'Colt', 'D150','Dakota', 'Daytona', 'Diplomat', 'Dynasty', 'Lancer', 'Omni','Raider','Ram 50', 'Ramcharger', 'Shadow', 'Spirit', 'Viper'],
            'GMC': [ 'Jimmy', 'Sierra', 'Suburban', ],
            'Ford': ['Bronco', 'EXP', 'Excort', 'F-Series', 'LTD', 'Mustang', 'Tempo', 'Thunderbird',  'Probe', 'Ranger', 'Taurus', 'Aerostar' ],
            'Toyota': ['4Runner', 'Supra', 'Mr-2', 'Previa', 'T100', 'Camry', 'Corolla', 'Land Cruiser',  ],
        },
        1990: {
            'BMW': [ '3-Series',  '7-Series', '8-Series', 'Z1'],
            'Hyundai': ['Excel', 'Scoupe', 'Sonata', ],
            'Chrysler': ['Imperial', 'LeBaron', 'New Yorker', 'TC', 'Town&Country', ],
            'Acrua': [ 'Intergra', 'Legend',  ],
            'Cadillac': ['Allante', 'Brougham', 'DeVille', 'Eldorado', 'Fleetwood', 'Seville', ],
            'Honda': ['Accord', 'CRX', 'Civic', 'Prelude', ],
            'Jeep': ['Comanche'],
            'Mazda': ['323', '626', '929', 'B-Series', 'MPV', 'MX', 'Miata', 'Navajo', 'Protege', 'RX7' ],
            'Dodge': ['B-Series', 'Caravan', 'Colt', 'D150','Dakota', 'Daytona', 'Dynasty','Monaco', 'Omni','Raider','Ram 50', 'Ramcharger', 'Shadow', 'Spirit',],
            'GMC': [ 'Jimmy', 'Savana', 'Sierra', 'Suburban', ],
            'Ford': ['Bronco', 'EXP', 'Excort', 'F-Series', 'LTD', 'Mustang', 'Tempo', 'Thunderbird',  'Probe', 'Ranger', 'Taurus', 'Aerostar' ],
            'Toyota': ['4Runner', 'Supra', 'Previa', 'T100', 'Camry', 'Corolla', 'Land Cruiser',  ],
        },
        1991: {
            'BMW': [ '3-Series',  '7-Series', '8-Series', 'Z1'],
            'Hyundai': ['Excel', 'Scoupe', 'Sonata', ],
            'Chrysler': ['Imperial', 'LeBaron', 'New Yorker', 'TC', 'Town&Country', ],
            'Acrua': [ 'Intergra', 'Legend', 'NSX',  ],
            'Cadillac': ['Allante', 'Brougham', 'DeVille', 'Eldorado', 'Fleetwood', 'Seville', ],
            'Honda': ['Accord', 'CRX', 'Civic', 'Prelude', ],
            'Jeep': ['Comanche'],
            'Mazda': ['323', '626', '929', 'B-Series', 'MPV', 'MX', 'Miata', 'Navajo', 'Protege', 'RX7' ],
            'Dodge': ['B-Series', 'Caravan', 'Colt', 'D150','Dakota', 'Daytona', 'Dynasty','Monaco','Ram 50', 'Ramcharger', 'Shadow', 'Spirit','Stealth'],
            'GMC': [ 'Jimmy', 'Savana', 'Sierra', 'Suburban', ],
            'Ford': ['Bronco', 'EXP', 'Excort', 'F-Series', 'LTD', 'Mustang', 'Tempo', 'Thunderbird',  'Probe', 'Ranger', 'Taurus', 'Aerostar' ],
            'Toyota': ['4Runner', 'Supra', 'Previa', 'T100', 'Tercel', 'Camry', 'Corolla', 'Land Cruiser',  'Rav4', 'Tacoma', ],
        },
        1992: {
            'BMW': [ '3-Series',  '7-Series', '8-Series',],
            'Hyundai': ['Excel', 'Elantra', 'Scoupe', 'Sonata', ],
            'Chrysler': ['Imperial', 'LeBaron', 'New Yorker', 'Town&Country', ],
            'Acrua': [ 'Intergra', 'Legend', 'NSX', 'Vigor' ],
            'Cadillac': ['Allante', 'Brougham', 'DeVille', 'Eldorado', 'Fleetwood', 'Seville', ],
            'Honda': ['Accord', 'Civic', 'Prelude', ],
            'Jeep': ['Comanche'],
            'Mazda': ['323', '626', '929', 'B-Series', 'MPV', 'MX', 'Miata', 'Navajo', 'Protege', 'RX7' ],
            'Dodge': ['B-Series', 'Caravan', 'Colt', 'D150','Dakota', 'Daytona', 'Dynasty','Monaco', 'Omni','Raider','Ram 50', 'Ramcharger', 'Shadow', 'Spirit',],
            'GMC': [ 'Jimmy', 'Savana', 'Sierra', 'Suburban', ],
            'Ford': ['Bronco', 'EXP', 'Excort', 'F-Series', 'Crown Victoria', 'Mustang', 'Tempo', 'Thunderbird',  'Probe', 'Ranger', 'Taurus', 'Aerostar' ],
            'Toyota': ['4Runner', 'Avalon', 'Supra', 'Previa', 'T100', 'Tercel', 'Camry', 'Corolla', 'Highlander', 'Land Cruiser',  'Rav4', 'Sequoia', 'Tacoma', ],
        },
        1993: {
            'BMW': [ '3-Series',  '7-Series', '8-Series',],
            'Hyundai': ['Excel', 'Elantra', 'Scoupe', 'Sonata', ],
            'Chrysler': ['Concorde', 'Imperial', 'LeBaron', 'New Yorker', 'Town&Country', ],
            'Acrua': [ 'Intergra', 'Legend', 'NSX', 'Vigor' ],
            'Cadillac': ['Allante', 'DeVille', 'Eldorado', 'Fleetwood', 'Seville', ],
            'Honda': ['Accord', 'Civic', 'Prelude', ],
            'Jeep': ['Grand Cherokee'],
            'Mazda': ['323', '626', '929', 'B-Series', 'MPV', 'MX', 'Navajo', 'Protege', 'RX7' ],
            'Dodge': ['B-Series', 'Caravan', 'Colt', 'D150','Dakota', 'Daytona', 'Dynasty','Intrepid','Ram 50', 'Ramcharger', 'Shadow', 'Spirit','Stealth', "Viper"],
            'GMC': [ 'Jimmy', 'Savana', 'Sierra', 'Suburban', ],
            'Ford': ['Bronco', 'EXP', 'Excort', 'F-Series', 'Crown Victoria', 'Mustang', 'Tempo', 'Thunderbird',  'Probe', 'Ranger', 'Taurus', 'Aerostar' ],
            'Toyota': ['4Runner', 'Avalon', 'Supra', 'Previa', 'T100', 'Tercel', 'Camry', 'Corolla', 'Highlander', 'Land Cruiser',  'Rav4', 'Sequoia', 'Tacoma', ],
        },
        1994: {
            'BMW': [ '3-Series',  '7-Series', '8-Series',],
            'Hyundai': ['Excel', 'Elantra', 'Scoupe', 'Sonata', ],
            'Chrysler': ['Concorde', 'LHS', 'LeBaron', 'New Yorker', 'Town&Country', ],
            'Acrua': [ 'Intergra', 'Legend', 'NSX', 'Vigor' ],
            'Cadillac': ['DeVille', 'Eldorado', 'Fleetwood', 'Seville', ],
            'Honda': ['Accord', 'Civic', 'Passport', 'Prelude', ],
            'Jeep': ['Grand Cherokee'],
            'Mazda': ['323', '626', '929', 'B-Series', 'MPV', 'MX', 'Millenia', 'Protege', 'RX7' ],
            'Dodge': ['B-Series', 'Caravan', 'Colt','Dakota','Expresso', 'Intrepid','Ram 1500', 'Shadow', 'Spirit','Stealth', "Viper"],
            'GMC': ['Envoy', 'Jimmy','Safari', 'Savana', 'Sierra', 'Suburban', 'Yukon', ],
            'Ford':  ['Bronco', 'EXP', 'Excort', 'F-Series', 'Crown Victoria', 'Mustang', 'Tempo', 'Thunderbird',  'Probe', 'Ranger', 'Taurus', 'Aerostar' ],
            'Toyota': ['4Runner', 'Avalon', 'Supra', 'Previa', 'T100', 'Tercel', 'Camry', 'Corolla', 'Highlander', 'Land Cruiser',  'Rav4', 'Sequoia', 'Tacoma', ],
        },
        1995: {
            'BMW': [ '3-Series',  '7-Series', '8-Series',],
            'Hyundai': ['Accent', 'Elantra', 'Sonata', ],
            'Chrysler': ['Cirrus', 'Concorde', 'LHS', 'LeBaron', 'New Yorker', 'Sebring', 'Town&Country', ],
            'Acrua': [ 'Intergra', 'Legend', 'NSX', ],
            'Cadillac': ['DeVille', 'Eldorado', 'Fleetwood', 'Seville', ],
            'Honda': ['Accord', 'Civic', 'Odyssey', 'Passport', 'Prelude', ],
            'Jeep': ['Cherokee', 'Grand Cherokee', 'Wrangler'],
            'Mazda': ['626', '929', 'B-Series', 'MPV', 'MX', 'Millenia', 'Protege', 'RX7' ],
            'Dodge': ['Avenger', 'Caravan','Dakota', 'Intrepid','Neon', 'Ram 1500','Ram', 'Spirit','Stealth','Stratus', 'Viper'],
            'GMC': ['Envoy', 'Jimmy','Safari', 'Savana', 'Sierra', 'Suburban', 'Yukon', ],
            'Ford': ['Bronco', 'EXP', 'Excort', 'F-Series', 'Crown Victoria', 'Mustang', 'Tempo', 'Thunderbird',  'Probe', 'Ranger', 'Taurus', 'Aerostar', 'Aspire', 'Contour', 'Windstar' ],
            'Toyota': ['4Runner', 'Avalon', 'Supra', 'T100', 'Tercel', 'Camry', 'Corolla', 'Highlander', 'Land Cruiser',  'Rav4', 'Sequoia', 'Tacoma', ],
        },
        1996: {
            'BMW': [ '3-Series',  '7-Series', '8-Series', 'Z3', ],
            'Hyundai': ['Accent', 'Elantra', 'Sonata', 'Tiburon', ],
            'Chrysler': ['Cirrus', 'Concorde', 'LHS', 'New Yorker', 'Sebring', 'Town&Country', ],
            'Acrua': [ 'Intergra', 'NSX', 'RL', 'SLX', 'TL', ],
            'Cadillac': ['DeVille', 'Eldorado', 'Fleetwood', 'Seville', ],
            'Honda': ['Accord', 'Civic', 'Odyssey', 'Passport', 'Prelude', ],
            'Jeep': ['Cherokee', 'Grand Cherokee', 'Rubicon'],
            'Mazda': ['626', 'B-Series', 'MPV', 'MX6', 'Millenia', 'Protege',  ],
            'Dodge': ['Avenger', 'Caravan','Dakota', 'Intrepid','Neon', 'Ram 1500','Ram','Stealth','Stratus', 'Viper'],
            'GMC': ['Envoy', 'Jimmy','Safari', 'Savana', 'Sierra', 'Suburban', 'Yukon', ],
            'Ford': ['Bronco', 'Explorer', 'EXP', 'Excort', 'F-Series', 'Crown Victoria', 'Mustang', 'Tempo', 'Thunderbird',  'Probe', 'Ranger', 'Taurus', 'Aerostar', 'Aspire', 'Contour', 'Windstar' ],
            'Toyota': ['4Runner', 'Avalon', 'Supra', 'T100', 'Tercel', 'Camry', 'Corolla', 'Highlander', 'Land Cruiser',  'Rav4', 'Sequoia', 'Tacoma', ],
        },
        1997: {
            'BMW': [ '3-Series', '5-Series', '7-Series', '8-Series', 'Z3', ],
            'Hyundai': ['Accent', 'Elantra', 'Sonata', 'Tiburon', ],
            'Chrysler': ['Cirrus', 'Concorde', 'LHS', 'Sebring', 'Town&Country', ],
            'Acrua': ['CL', 'Intergra', 'NSX', 'RL', 'SLX', 'TL', ],
            'Cadillac': ['Catera', 'DeVille', 'Eldorado', 'Seville', ],
            'Honda': ['Accord', 'CR-V', 'Civic', 'Odyssey', 'Passport', 'Prelude',  ],
            'Jeep': ['Cherokee', 'Grand Cherokee', 'Wrangler'],
            'Mazda': ['626', 'B-Series', 'MPV', 'MX6', 'Millenia', 'Protege',  ],
            'Dodge': ['Avenger','Caravan','Dakota', 'Intrepid','Neon', 'Ram 1500','Ram','Stratus', 'Viper'],
            'GMC': ['Envoy', 'Jimmy','Safari', 'Savana', 'Sierra', 'Suburban', 'Yukon', ],
            'Ford': ['Bronco', 'Explorer', 'EXP', 'Excort', 'F-Series', 'Crown Victoria', 'Mustang', 'Tempo', 'Thunderbird',  'Probe', 'Ranger', 'Taurus', 'Aerostar', 'Aspire', 'Contour', 'Windstar' ],
            'Toyota': ['4Runner', 'Avalon', 'Supra', 'T100', 'Tercel', 'Camry', 'Corolla', 'Highlander', 'Land Cruiser',  'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', ],
        },
        1998: {
            'BMW': [ '3-Series', '5-Series', '7-Series', 'Z3', ],
            'Hyundai': ['Accent', 'Elantra', 'Sonata', 'Tiburon', ],
            'Chrysler': ['Cirrus', 'Concorde', 'Sebring', 'Town&Country', ],
            'Acrua': ['CL', 'Intergra', 'NSX', 'RL', 'SLX', 'TL', ],
            'Cadillac': ['Catera', 'DeVille', 'Eldorado', 'Seville', ],
            'Honda': ['Accord', 'CR-V', 'Civic', 'Odyssey', 'Passport', 'Prelude',  ],
            'Jeep': ['Cherokee', 'Grand Cherokee', 'Wrangler'],
            'Mazda': ['B-Series', 'MPV', 'Miata', 'Millenia', 'Protege', ],
            'Dodge': ['Avenger','Caravan','Dakota','Durango', 'Intrepid','Neon', 'Ram 1500','Ram','Stratus', 'Viper'],
            'GMC': ['Envoy', 'Jimmy','Safari', 'Savana', 'Sierra', 'Suburban', 'Yukon', ],
            'Ford': ['Bronco', 'Explorer', 'EXP', 'Excort', 'F-Series', 'Crown Victoria', 'Mustang', 'Tempo', 'Thunderbird',  'Probe', 'Ranger', 'Taurus', 'Aerostar', 'Aspire', 'Contour', 'Windstar' ],
            'Toyota': ['4Runner', 'Avalon', 'Supra', 'T100', 'Tercel', 'Camry', 'Corolla', 'Highlander', 'Land Cruiser',  'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', ],
        },
        1999: {
            'BMW': [ '3-Series', '5-Series', '7-Series', 'Z3', ],
            'Hyundai': ['Accent', 'Elantra', 'Sonata', 'Tiburon', ],
            'Chrysler': ['Cirrus', 'Concorde', 'LHS', 'Sebring', 'Town&Country',  ],
            'Acrua': ['CL', 'Intergra', 'NSX', 'SLX', 'TL', ],
            'Cadillac': ['Catera', 'DeVille', 'Eldorado', 'Escalade', 'Seville', ],
            'Honda': ['Accord', 'CR-V', 'Civic', 'Odyssey', 'Passport', 'Prelude',  ],
            'Jeep': ['Cherokee', 'Grand Cherokee', 'Wrangler'],
            'Mazda': ['626', 'B-Series', 'MP3', 'MPV', 'Miata', 'Millenia', 'Protege', ],
            'Dodge': ['Avenger','Caravan','Dakota','Durango', 'Intrepid','Neon', 'Ram 1500','Ram','Stratus', 'Viper'],
            'GMC': ['Envoy', 'Jimmy','Safari', 'Savana', 'Sierra', 'Suburban', 'Yukon', ],
            'Ford': ['Explorer', 'Excort', 'F-Series', 'Crown Victoria', 'Mustang', 'Thunderbird',  'Probe', 'Ranger', 'Taurus', 'Aerostar', 'Expedition', ],
            'Toyota': ['4Runner', 'Avalon',  'Camry', 'Echo', 'Celica', 'Corolla', 'Highlander', 'Land Cruiser',  'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', ],
        },
        2000: {
            'BMW': [ '3-Series', '5-Series', '7-Series', 'X5', 'Z3', ],
            'Hyundai': ['Accent', 'Elantra', 'Sonata', 'Tiburon', ],
            'Chrysler': ['Cirrus', 'Concorde', 'LHS', 'Sebring', 'Town&Country',  ],
            'Acrua': ['Intergra', 'NSX', 'RL', 'TL', ],
            'Cadillac': ['Catera', 'DeVille', 'Eldorado', 'Escalade', 'Seville', ],
            'Honda': ['Accord', 'CR-V', 'Civic', 'Insight', 'Odyssey', 'Passport', 'Prelude', 'S2000' ],
            'Jeep': ['Cherokee', 'Grand Cherokee', 'Wrangler'],
            'Mazda': ['626', 'B-Series', 'MP3', 'MPV', 'Miata', 'Millenia', 'Protege', ],
            'Dodge': ['Avenger','Caravan','Dakota','Durango', 'Intrepid','Neon', 'Ram 1500','Ram','Stratus', 'Viper'],
            'GMC': ['Envoy', 'Jimmy','Safari', 'Savana', 'Sierra', 'Yukon', ],
            'Ford': ['Explorer', 'Excort', 'F-Series', 'Crown Victoria', 'Mustang', 'Thunderbird',  'Ranger', 'Taurus', 'E-van', 'Expedition', 'Excursion', 'Focus' ],
            'Toyota': ['4Runner', 'Avalon',  'Camry', 'Echo', 'MR2 Spyder', 'Celica', 'Corolla', 'Highlander', 'Land Cruiser', 'MR2 Syyder', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra' ],
        },
        2001: {
            'BMW': [ '3-Series', '5-Series', '7-Series', 'X5', 'Z3', 'Z8' ],
            'Hyundai': ['Accent', 'Elantra', 'Santa Fe', 'Sonata', 'Tiburon', 'XG300' ],
            'Chrysler': ['300M', 'Concorde', 'LHS', 'PT Cruiser', 'Prowler', 'Sebring', 'Town&Country', 'Voyager' ],
            'Acrua': ['CL', 'Intergra', 'MDX', 'NSX', 'RL', 'TL', ],
            'Cadillac': ['Catera', 'DeVille', 'Eldorado', ],
            'Honda': ['Accord', 'CR-V', 'Civic', 'Insight', 'Odyssey', 'Passport', 'Prelude', 'S2000' ],
            'Jeep': ['Cherokee', 'Grand Cherokee', 'Wrangler'],
            'Mazda': ['626', 'B-Series', 'MP3', 'MPV', 'Miata', 'Millenia', 'Protege', 'Tribute' ],
            'Dodge': ['Caravan','Dakota','Durango', 'Intrepid','Neon', 'Ram 1500','Ram','Stratus', 'Viper'],
            'GMC': ['Jimmy','Safari', 'Savana', 'Sierra', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Crown Victoria', 'Mustang', 'Thunderbird', 'Ranger', 'Taurus', 'E-van', 'Contour','Expedition', 'Excursion', 'Focus' ],
            'Toyota': ['4Runner', 'Avalon',  'Camry', 'Echo', 'MR2 Spyder', 'Celica', 'Corolla', 'Highlander', 'Land Cruiser', 'MR2 Syyder', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra' ],
        },
        2002: {
            'BMW': [ '3-Series', '5-Series', '7-Series', 'X5', 'Z3', 'Z8' ],
            'Hyundai': ['Accent', 'Elantra', 'Santa Fe', 'Sonata', 'Tiburon', 'XG350' ],
            'Chrysler': ['300M', 'Concorde',  'PT Cruiser', 'Prowler', 'Sebring', 'Town&Country', 'Voyager' ],
            'Acrua': ['CL', 'MDX', 'NSX', 'RSX', 'RL', 'TL', ],
            'Cadillac': ['Catera', 'DeVille', 'Eldorado', 'Escalade', 'Seville',],
            'Honda': ['Accord', 'CR-V', 'Civic', 'Elemnt', 'Insight', 'Odyssey', 'S2000' ],
            'Jeep': [ 'Grand Cherokee','Liberty', 'Wrangler'],
            'Mazda': ['626', 'B-Series', 'MP3', 'MPV', 'Miata', 'Millenia', 'Protege', 'Tribute' ],
            'Dodge': ['Caravan','Dakota','Durango', 'Intrepid','Neon', 'Ram 1500','Ram','Stratus', 'Viper'],
            'GMC': ['Envoy', 'Safari', 'Savana', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Crown Victoria', 'Mustang', 'Thunderbird', 'Ranger', 'Taurus', 'Expedition', 'Excursion', 'Focus' ],
            'Toyota': ['4Runner', 'Avalon',  'Camry', 'Echo', 'MR2 Spyder', 'Celica', 'Corolla', 'Highlander', 'Land Cruiser', 'MR2 Syyder', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra' ],
        },
        2003: {
            'BMW': [ '3-Series', '5-Series', '7-Series', 'M3', 'M5', 'Z4', ],
            'Hyundai': ['Accent', 'Elantra', 'Santa Fe', 'Sonata', 'Tiburon', 'XG350' ],
            'Chrysler': ['300M', 'Concorde',  'PT Cruiser', 'Sebring', 'Town&Country', 'Voyager' ],
            'Acrua': ['CL', 'MDX', 'NSX', 'RSX', 'RL', 'TL', ],
            'Cadillac': ['CTS', 'DeVille', 'Escalade', 'Seville',],
            'Honda': ['Accord', 'CR-V', 'Civic', 'FCX', 'Elemnt', 'Insight', 'Odyssey', 'Pilot', 'S2000' ],
            'Jeep': [ 'Grand Cherokee','Liberty', 'Wrangler'],
            'Mazda': ['B-Series', 'Miata', 'Mazda6', 'MPV', 'Truibut', 'Protege', ],
            'Dodge': ['Caravan','Dakota','Durango', 'Intrepid','Neon', 'Ram 1500', 'Ram 2500/3500','Ram','Sprinter', 'Stratus', 'Viper', ],
            'GMC': ['Canyon', 'Envoy', 'Safari', 'Savana', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Crown Victoria', 'Mustang', 'Thunderbird', 'Ranger', 'Taurus', 'Expedition', 'Excursion', 'Focus', 'Thunderbird', 'Windstar', 'ZX2' ],
            'Toyota': ['4Runner', 'Avalon',  'Camry', 'Celica', 'Corolla', 'FJ Cruiser',  'Highlander', 'Land Cruiser', 'MR2 Spyder', 'Matrix', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra' ],
        },
        2004: {
            'BMW': [ '3-Series', '5-Series', '6-Series', '7-Series', 'M3', 'X3', 'X5', 'Z4', ],
            'Hyundai': ['Accent', 'Elantra', 'Santa Fe', 'Sonata', 'Tiburon', 'XG350' ],
            'Chrysler': ['300M', 'Concorde', 'Crossfire', 'PT Cruiser', 'Pacifica', 'Sebring', 'Town&Country', ],
            'Acrua': ['MDX', 'NSX', 'RSX', 'RL', 'TL', 'TSX', ],
            'Cadillac': ['CTS', 'DeVille', 'Escalade', 'SRX','SLS', 'XLR'],
            'Honda': ['Accord', 'CR-V', 'Civic', 'Elemnt', 'Insight', 'Odyssey', 'Pilot', 'S2000' ],
            'Jeep': [ 'Grand Cherokee','Liberty', 'Wrangler'],
            'Mazda': ['B-Series', 'CX', 'MX-5', 'Mazda5', 'Mazda3', 'Mazda6', 'MPV', 'RX8', 'Truibut', ],
            'Dodge': ['Caravan','Dakota','Durango', 'Intrepid','Neon', 'Ram 1500','Ram 2500/3500','Ram','Sprinter', 'Stratus', 'Viper SRT-10' ],
            'GMC': ['Canyon', 'Envoy', 'Safari', 'Savana', 'Sierra', 'Terrain', 'Sonoma', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Crown Victoria', 'Mustang', 'Thunderbird', 'Ranger', 'Taurus', 'Expedition', 'Excursion', 'Focus', 'Thunderbird', 'Freestar', 'ZX2' ],
            'Toyota': ['4Runner', 'Avalon',  'Camry', 'Celica', 'Corolla', 'FJ Cruiser',  'Highlander', 'Land Cruiser', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', ]
        },
        2005: {
            'BMW': [ '3-Series', '5-Series', '6-Series', '7-Series', 'M3', 'X3', 'X5', 'Z4', ],
            'Hyundai': ['Accent', 'Elantra', 'Santa Fe', 'Sonata', 'Tiburon', 'Tucson', 'ZG350' ],
            'Chrysler': ['300', 'Crossfire', 'PT Cruiser', 'Pacifica', 'Sebring', 'Town&Country', ],
            'Acrua': ['MDX', 'NSX', 'RSX', 'RL', 'TL', 'TSX', ],
            'Cadillac': ['CTS', 'DeVille', 'Escalade', 'SRX','STS', 'XLR'],
            'Honda': ['Accord', 'CR-V', 'Civic', 'Elemnt', 'FCX', 'Insight', 'Odyssey', 'Pilot', 'S2000' ],
            'Jeep': [ 'Grand Cherokee','Liberty', 'Wrangler', 'Wrangler Unlimited'],
            'Mazda': ['B-Series', 'CX', 'MX-5', 'Mazda5', 'Mazda3', 'Mazda6', 'MPV', 'RX8', 'Truibut', ],
            'Dodge': ['Caravan','Dakota','Durango', 'Magnum','Neon', 'Ram 1500','Ram 2500/3500','Sprinter', 'Stratus', 'Viper SRT-10' ],
            'GMC': ['Canyon', 'Envoy', 'Safari', 'Savana', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Crown Victoria', 'Mustang', 'Thunderbird', 'Ranger', 'Taurus', 'Expedition', 'Excursion', 'Focus', 'Thunderbird', 'Freestar', 'ZX2', 'Five Hundred', 'GT' ],
            'Toyota': ['4Runner', 'Avalon',  'Camry', 'Corolla', 'Echo', 'FJ Cruiser',  'Highlander', 'Land Cruiser', 'MR2 Spyder', 'Matrix', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', ]
        },
        2006: {
            'BMW': [ '3-Series', '5-Series', '6-Series', '7-Series', 'M3', 'M5', 'M6', 'X3', 'X5', 'Z4', ],
            'Hyundai': ['Accent', 'Azera', 'Elantra', 'Santa Fe', 'Sonata', 'Tiburon', 'Tucson', ],
            'Chrysler': ['300', 'PT Cruiser', 'Pacifica', 'Sebring', 'Town&Country', ],
            'Acrua': ['MDX', 'RDX', 'RL', 'TL', 'TSX', ],
            'Cadillac': ['CTS', 'DTS', 'Escalade', 'SRX','STS', 'XLR'],
            'Honda': ['Accord', 'CR-V', 'Civic', 'Elemnt', 'FCX', 'Insight', 'Odyssey', 'Pilot', 'Ridgeline', 'S2000' ],
            'Jeep': [ 'Commander', 'Grand Cherokee', 'Liberty', 'Wrangler', 'Wrangler Unlimited'],
            'Mazda': ['B-Series', 'CX', 'MX-5', 'Mazda5', 'Mazda3', 'Mazda6', 'MPV', 'RX8', 'Truibut', ],
            'Dodge': ['Caravan','Charger','Dakota','Durango', 'Magnum','Neon', 'Ram 1500','Ram 2500/3500','Sprinter', 'Stratus', 'Viper' ],
            'GMC': ['Acadia', 'Canyon', 'Envoy', 'Savana', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Crown Victoria', 'Mustang', 'Thunderbird', 'Ranger', 'Taurus', 'Expedition', 'Excursion', 'Focus', 'Thunderbird', 'Freestar', 'ZX2', 'Five Hundred', 'GT', 'Fusion' ],
            'Toyota': ['4Runner', 'Avalon',  'Camry', 'Corolla', 'FJ Cruiser',  'Highlander', 'Land Cruiser', 'Matrix', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', ],
        },
        2007: {
            'BMW': [ '3-Series', '5-Series', '6-Series', '7-Series', 'M5', 'M6', 'X3', 'X5', 'X6', 'Z4', ],
            'Hyundai': ['Accent', 'Azera', 'Elantra', 'Entourage', 'Santa Fe', 'Sonata', 'Tiburon', 'Tucson', 'Veracruz'],
            'Chrysler': ['300', 'Aspen', 'Crossfire', 'PT Cruiser', 'Pacifica', 'Sebring', 'Town&Country', ],
            'Acrua': ['MDX', 'RDX', 'RL', 'TL', 'TSX', ],
            'Cadillac': ['CTS', 'DTS', 'Escalade', 'SRX','STS', 'XLR'],
            'Honda': ['Accord', 'CR-V', 'Civic', 'Elemnt', 'Fit', 'Odyssey', 'Pilot', 'Ridgeline', 'S2000' ],
            'Jeep': [ 'Commander', 'Compass', 'Grand Cherokee', 'Liberty', 'Patriot', 'Wrangler', 'Wrangler Unlimited'],
            'Mazda': ['B-Series', 'CX', 'MX-5', 'Mazda5', 'Mazda3', 'Mazda6', 'RX8', 'Truibut', ],
            'Dodge': ['Caliber','Caravan','Charger','Dakota','Durango', 'Magnum','Nitro', 'Ram 1500','Ram 2500/3500','Sprinter', 'Stratus', 'Viper' ],
            'GMC': ['Acadia', 'Canyon', 'Envoy', 'Savana', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Crown Victoria', 'Mustang',  'Expedition', 'Excursion', 'Focus', 'Freestar', 'ZX2', 'Five Hundred', 'GT', 'Fusion', 'Edge' ],
            'Toyota': ['4Runner', 'Avalon',  'Camry', 'Corolla', 'FJ Cruiser',  'Highlander', 'Land Cruiser', 'Matrix', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Yaris', ],
        },
        2008: {
            'BMW': ['1-Series', '3-Series', '5-Series', '6-Series', '7-Series', 'M3', 'M5', 'M6', 'X3', 'X5', 'X6', 'Z4', ],
            'Hyundai': ['Accent', 'Azera', 'Elantra', 'Entourage', 'Santa Fe', 'Sonata', 'Tiburon', 'Tucson', 'Veracruz'],
            'Chrysler': ['300', 'Aspen', 'Crossfire', 'PT Cruiser', 'Pacifica', 'Sebring', 'Town&Country', ],
            'Acrua': ['MDX', 'RDX', 'RL', 'TL', 'TSX', ],
            'Cadillac': ['CTS', 'DTS', 'Escalade', 'SRX','STS', 'XLR'],
            'Honda': ['Accord', 'CR-V', 'Civic', 'Elemnt', 'Fit', 'Odyssey', 'Pilot', 'Ridgeline', 'S2000' ],
            'Jeep': [ 'Commander', 'Compass', 'Grand Cherokee', 'Liberty', 'Patriot', 'Wrangler', 'Wrangler Unlimited'],
            'Mazda': ['B-Series', 'CX', 'MX-5', 'Mazda5', 'Mazda3', 'Mazda6', 'RX8', 'Truibut', ],
            'Dodge': ['Avenger', 'Caliber','Challenger','Charger','Dakota','Durango','Grand Caravan', 'Magnum','Nitro', 'Ram 1500','Ram 2500/3500','Ram 4500/5500','Sprinter', 'Viper' ],
            'GMC': ['Acadia', 'Canyon', 'Envoy', 'Savana', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Crown Victoria', 'Mustang',  'Expedition', 'Excursion', 'Focus', 'Freestar', 'ZX2', 'Five Hundred', 'Fusion', 'Edge', 'Ranger', 'Taurus' ],
            'Toyota': ['4Runner', 'Avalon',  'Camry', 'Corolla', 'FJ Cruiser',  'Highlander', 'Land Cruiser', 'Matrix', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Yaris', ],
        },
        2009: {
            'BMW': ['1-Series', '3-Series', '5-Series', '6-Series', '7-Series', 'M5', 'M6', 'X3', 'X5', 'X6', 'Z4', ],
            'Hyundai': ['Accent', 'Azera', 'Elantra', 'Genesis', 'Santa Fe', 'Sonata', 'Tucson', 'Veracruz'],
            'Chrysler': ['300', 'Aspen', 'PT Cruiser', 'Sebring', 'Town&Country', ],
            'Acrua': ['MDX', 'RDX', 'RL', 'TL', 'TSX', ],
            'Cadillac': ['CTS', 'DTS', 'Escalade', 'SRX','STS', 'XLR'],
            'Honda': ['Accord', 'CR-V', 'Civic', 'Elemnt', 'Clarity', 'Insight', 'Fit', 'Odyssey', 'Pilot', 'Ridgeline', 'S2000' ],
            'Jeep': [ 'Commander', 'Compass', 'Grand Cherokee', 'Liberty', 'Patriot', 'Wrangler', 'Wrangler Unlimited'],
            'Mazda': ['B-Series', 'CX', 'MX-5', 'Mazda5', 'Mazda3', 'Mazda6', 'RX8', 'Truibut', ],
            'Dodge': ['Avenger', 'Caliber','Challenger','Charger','Dakota','Durango','Grand Caravan', 'Journey','Nitro', 'Ram 1500','Ram 2500/3500','Ram 4500/5500','Sprinter', 'Viper' ],
            'GMC': ['Acadia', 'Canyon', 'Envoy', 'Savana', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Mustang',  'Expedition', 'Focus', 'Fusion', 'Edge', 'Ranger', 'Taurus', 'Flex' ],
            'Toyota': ['4Runner', 'Avalon',  'Camry', 'Corolla', 'FJ Cruiser',  'Highlander', 'Land Cruiser', 'Matrix', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Yaris', ],
        },
        2010: {
            'BMW': ['1-Series', '3-Series', '5-Series', '6-Series', '7-Series', 'M5', 'M6', 'X3', 'X5', 'X6', 'Z4', ],
            'Hyundai': ['Accent', 'Azera', 'Elantra', 'Genesis', 'Santa Fe', 'Sonata', 'Tucson', 'Veracruz'],
            'Chrysler': ['300', 'PT Cruiser', 'Sebring', 'Town&Country', ],
            'Acrua': ['MDX', 'RDX', 'RL', 'TL', 'TSX', 'ZDX',],
            'Cadillac': ['CTS', 'DTS', 'Escalade', 'SRX','STS'],
            'Honda': ['Accord', 'CR-V', 'Civic', 'Elemnt', 'Clarity', 'Insight', 'Fit', 'Odyssey', 'Pilot', 'Ridgeline' ],
            'Jeep': [ 'Commander', 'Compass', 'Grand Cherokee', 'Liberty', 'Patriot', 'Wrangler', 'Wrangler Unlimited'],
            'Mazda': ['CX', 'MX-5', 'Mazda5', 'Mazda3', 'Mazda6', 'RX8', 'Truibut', ],
            'Dodge': ['Avenger', 'Caliber','Challenger','Charger','Dakota','Grand Caravan', 'Journey','Nitro', 'Ram 1500','Ram 2500/3500','Ram 4500/5500', 'Viper' ],
            'GMC': ['Acadia', 'Canyon', 'Savana', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford':  ['Explorer', 'F-Series', 'Mustang',  'Expedition', 'Focus', 'Fusion', 'Edge', 'Ranger', 'Taurus', 'Flex', 'Fiesta',  ],
            'Toyota': ['4Runner', 'Avalon',  'Camry', 'Corolla', 'FJ Cruiser',  'Highlander', 'Land Cruiser', 'Matrix', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Yaris', ],
        },
        2011: {
            'BMW': ['1-Series', '3-Series', '5-Series', '6-Series', '7-Series', 'X3', 'X5', 'X6', 'Z4', ],
            'Hyundai': ['Accent', 'Azera', 'Elantra', 'Equus', 'Genesis', 'Santa Fe', 'Sonata', 'Tucson', 'Veracruz'],
            'Chrysler': ['200', '300', 'Town&Country', ], 
            'Acrua': ['MDX', 'RDX', 'RL', 'TL', 'TSX', 'ZDX',],
            'Cadillac': ['CTS', 'DTS', 'Escalade', 'SRX','STS'],
            'Honda': ['Accord', 'CR-V', 'CR-Z', 'Civic', 'Elemnt', 'Clarity', 'Insight', 'Fit', 'Odyssey', 'Pilot', 'Ridgeline' ],
            'Jeep': [ 'Compass', 'Grand Cherokee', 'Liberty', 'Patriot', 'Wrangler', 'Wrangler Unlimited'],
            'Mazda': ['CX', 'MX-5', 'Mazda2', 'Mazda5', 'Mazda3', 'Mazda6' ],
            'Ram': ['Dakota', '1500', '2500', '3500'],
            'Dodge': ['Avenger', 'Caliber','Challenger','Charger','Durango','Grand Caravan', 'Journey','Nitro'],
            'GMC': ['Acadia', 'Canyon', 'Savana', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford':  ['Explorer', 'F-Series', 'Mustang',  'Expedition', 'Focus', 'Fusion', 'Edge', 'Ranger', 'Taurus', 'Flex', 'Fiesta',  ],
            'Toyota': ['4Runner', 'Avalon',  'Camry', 'Corolla', 'FJ Cruiser',  'Highlander', 'Land Cruiser', 'Matrix', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Yaris', ],
        },
        2012: {
            'BMW': ['1-Series', '3-Series', '5-Series', '6-Series', '7-Series', 'X3', 'X5', 'X6', 'Z4', ],
            'Hyundai': ['Accent', 'Azera', 'Elantra', 'Equus', 'Genesis', 'Santa Fe', 'Sonata', 'Tucson', 'Veloster', 'Veracruz'],
            'Chrysler': ['200', '300', 'Town&Country', ],
            'Acrua': ['MDX', 'RDX', 'TL', 'TSX', 'ZDX',],
            'Cadillac': ['CTS', 'Escalade', 'SRX',],
            'Honda': ['Accord', 'CR-V', 'CR-Z', 'Civic', 'Fit', 'Crosstour', 'Insight', 'Odyssey', 'Pilot', 'Ridgeline' ],
            'Jeep': [ 'Compass', 'Grand Cherokee', 'Liberty', 'Patriot', 'Wrangler', 'Wrangler Unlimited'],
            'Mazda': ['CX', 'MX-5', 'Mazda2', 'Mazda5', 'Mazda3', 'Mazda6' ],
            'Ram': ['Cargo Van', 'Dakota', '1500', '2500', '3500'],
            'Dodge': ['Avenger', 'Caliber','Challenger','Charger','Durango','Grand Caravan', 'Journey'],
            'GMC': ['Acadia', 'Canyon', 'Savana', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Mustang',  'Expedition', 'Focus', 'Fusion', 'Edge', 'Ranger', 'Taurus', 'Flex', 'Fiesta',  ],
            'Toyota': ['4Runner', 'Avalon',  'Camry', 'Corolla', 'FJ Cruiser',  'Highlander', 'Land Cruiser', 'Matrix', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Yaris', ],
        },
        2013: {
            'BMW': ['1-Series', '3-Series', '5-Series', '6-Series', '7-Series', 'X1', 'X3', 'X5', 'X6', 'Z4', ],
            'Hyundai': ['Accent', 'Azera', 'Elantra', 'Equus', 'Genesis', 'Santa Fe', 'Sonata', 'Tucson', 'Veloster'],
            'Chrysler': ['200', '300', 'Town&Country', ],
            'Acrua': ['ILX', 'MDX', 'RDX', 'RLX', 'TL', 'TSX', 'ZDX',],
            'Cadillac': ['ATS', 'CTS', 'Escalade', 'SRX', 'XTS',],
            'Honda': ['Accord', 'CR-V', 'CR-Z', 'Civic', 'Fit', 'Crosstour', 'Insight', 'Odyssey', 'Pilot', 'Ridgeline' ],
            'Jeep': [ 'Compass', 'Grand Cherokee', 'Patriot', 'Wrangler', 'Wrangler Unlimited'],
            'Mazda': ['CX', 'MX-5', 'Mazda2', 'Mazda5', 'Mazda3', 'Mazda6' ],
            'Ram': ['Cargo Van', '1500', '2500', '3500'],
            'Dodge': ['Avenger','Challenger','Charger','Dart','Durango','Grand Caravan', 'Journey'],
            'GMC': ['Acadia', 'Savana', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Mustang',  'Expedition', 'Focus', 'Fusion', 'Edge', 'Ranger', 'Taurus', 'Flex', 'Fiesta',  ],
            'Toyota': ['4Runner', 'Avalon',  'Camry', 'Corolla', 'FJ Cruiser',  'Highlander', 'Land Cruiser', 'Matrix', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Yaris', ],
        },
        2014: {
            'BMW': ['2-Series', '3-Series', '4-Series', '5-Series', '6-Series', '7-Series', 'X1', 'X3', 'X5', 'X6', 'i3', 'Z4', 'i8' ],
            'Hyundai': ['Accent', 'Azera', 'Elantra', 'Equus', 'Genesis', 'Santa Fe', 'Sonata', 'Tucson', 'Veloster'],
            'Chrysler': ['200', '300', 'Town&Country', ],
            'Acrua': ['ILX', 'MDX', 'RDX', 'RLX', 'TL', 'TSX',],
            'Cadillac': ['ATS', 'CTS', 'ELR', 'Escalade', 'SRX', 'XTS',],
            'Honda': ['Accord', 'CR-V', 'CR-Z', 'Civic', 'Crosstour', 'Insight', 'Odyssey', 'Pilot', 'Ridgeline' ],
            'Jeep': ['Cherokee', 'Compass', 'Grand Cherokee', 'Patriot','Renegade', 'Wrangler', 'Wrangler Unlimited'],
            'Mazda': ['CX', 'MX-5', 'Mazda2', 'Mazda5', 'Mazda3', 'Mazda6' ],
            'Ram': ['Cargo Van', 'ProMaster',  '1500', '2500', '3500'],
            'Dodge': ['Avenger','Challenger','Charger','Dart','Durango','Grand Caravan', 'Journey'],
            'GMC': ['Acadia', 'Savana', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Mustang',  'Expedition', 'Focus', 'Fusion', 'Edge', 'Ranger', 'Taurus', 'Flex', 'Fiesta',  ],
            'Toyota': ['4Runner', 'Avalon',  'Camry', 'Corolla',  'Highlander', 'Land Cruiser', 'Venza', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Yaris', ],
        },
        2015: {
            'BMW': ['2-Series', '3-Series', '4-Series', '5-Series', '6-Series', '7-Series', 'X1', 'X3', 'X4', 'X5', 'Z4', 'X6', 'i3', 'i8' ],
            'Hyundai': ['Accent', 'Azera', 'Elantra', 'Equus', 'Genesis', 'Santa Fe', 'Sonata', 'Tucson', 'Veloster'],
            'Chrysler': ['200', '300', 'Town&Country', ],
            'Acrua': ['ILX', 'MDX', 'RDX', 'RLX', 'TLX',],
            'Cadillac': ['ATS', 'CTS', 'Escalade', 'SRX', 'XTS',],
            'Honda': ['Accord', 'CR-V', 'CR-Z', 'Civic', 'Crosstour', 'Fit', 'Odyssey', 'Pilot',  ],
            'Jeep': ['Cherokee', 'Compass', 'Grand Cherokee', 'Patriot','Renegade', 'Wrangler', 'Wrangler Unlimited'],
            'Mazda': ['CX', 'MX-5', 'Mazda5', 'Mazda3', 'Mazda6' ],
            'Ram': ['Cargo Van', 'ProMaster',  '1500', '2500', '3500'],
            'Dodge': ['Challenger','Charger','Dart','Durango','Grand Caravan', 'Journey', 'Viper'],
            'GMC': ['Acadia', 'Canyon', 'Savana', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Mustang',  'Expedition', 'Focus', 'Fusion', 'Edge', 'Ranger', 'Taurus', 'Flex', 'Fiesta',  ],
            'Toyota': ['4Runner', 'Avalon',  'Camry', 'Corolla',  'Highlander', 'Land Cruiser', 'Mirai', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Yaris', ],
        },
        2016: {
            'BMW': ['2-Series', '3-Series', '4-Series', '5-Series', '6-Series', '7-Series', 'X1', 'X3', 'X4', 'X5', 'X6', 'i3', 'i8' ],
            'Hyundai': ['Accent', 'Azera', 'Elantra', 'Equus', 'Genesis', 'Santa Fe', 'Sonata', 'Tucson', 'Veloster'],
            'Chrysler': ['200', '300', 'Town&Country', ],
            'Acrua': ['ILX', 'MDX', 'RDX', 'RLX', 'TLX',],
            'Cadillac': ['ATS', 'CT6', 'CTS', 'ELR', 'Escalade', 'SRX', 'XTS',],
            'Honda': ['Accord', 'CR-V', 'CR-Z', 'Civic', 'Fit', 'HR-V', 'Odyssey', 'Pilot',  ],
            'Mazda': ['CX', 'MX-5', 'Mazda3', 'Mazda6' ],
            'Ram': [ 'ProMaster',  '1500', '2500', '3500'],
            'Dodge': ['Challenger','Charger','Dart','Durango','Grand Caravan', 'Journey', 'Viper'],
            'GMC': ['Acadia', 'Canyon', 'Savana', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Mustang',  'Expedition', 'Focus', 'Fusion', 'Edge', 'Ranger', 'Taurus', 'Flex', 'Fiesta', 'Escape',  ],
            'Toyota':  ['4Runner', 'Avalon',  'Camry', 'Corolla',  'Highlander', 'Land Cruiser', 'Mirai', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Yaris', ],
        },
        2017: {
            'BMW': ['2-Series', '3-Series', '4-Series', '5-Series', '6-Series', '7-Series', 'X1', 'X3', 'X4', 'X5', 'X6', 'i3', ],
            'Hyundai': ['Accent', 'Azera', 'Elantra', 'Ioniq', 'Santa Fe', 'Sonata', 'Tucson', 'Veloster'],
            'Chrysler': ['200', '300', 'Pacifica', ],
            'Acrua': ['ILX', 'MDX', 'NSX', 'RDX', 'RLX', 'TLX',],
            'Cadillac': ['ATS', 'CT6', 'CTS', 'Escalade', 'XT5', 'XTS',],
            'Honda': ['Accord', 'CR-V', 'Civic', 'Clarity', 'Fit', 'HR-V', 'Odyssey', 'Pilot', 'Ridgeline', ],
            'Jeep': ['Cherokee', 'Compass', 'Grand Cherokee','Renegade', 'Wrangler', 'Wrangler Unlimited'],
            'Mazda': ['CX', 'MX-5', 'Mazda3', 'Mazda6' ],
            'Ram': [ 'ProMaster',  '1500', '2500', '3500'],
            'Dodge': ['Challenger','Charger','Durango','Grand Caravan', 'Journey', 'Viper'],
            'GMC': ['Acadia', 'Canyon', 'Savana', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Mustang',  'Expedition', 'Focus', 'Fusion', 'Edge', 'Taurus', 'Flex', 'Fiesta', 'Escape', 'GT'  ],
            'Toyota': ['4Runner', 'Avalon', 'C-HR', 'Camry', '86', 'Corolla', 'Highlander', 'Land Cruiser', 'Mirai', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Yaris', ],
        },
        2018: {
            'BMW': ['2-Series', '3-Series', '4-Series', '5-Series', '6-Series', '7-Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'i3', ],
            'Hyundai': ['Accent', 'Elantra', 'Ioniq', 'Kona', 'Santa Fe', 'Sonata', 'Tucson', ],
            'Chrysler': ['300', 'Pacifica', ],
            'Acrua': ['ILX', 'MDX', 'NSX', 'RDX', 'RLX', 'TLX',],
            'Cadillac': ['ATS', 'CT6', 'CTS', 'Escalade', 'XT5', 'XTS',],
            'Honda': ['Accord', 'CR-V', 'Civic', 'Clarity', 'Fit', 'HR-V', 'Odyssey', 'Pilot', 'Ridgeline', ],
            'Mazda': ['CX', 'MX-5', 'Mazda3', 'Mazda6' ],
            'Ram': [ 'ProMaster',  '1500', '2500', '3500'],
            'Dodge': ['Challenger','Charger','Durango','Grand Caravan', 'Journey'],
            'GMC': ['Acadia', 'Canyon', 'Savana', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Mustang',  'Expedition', 'Focus', 'Fusion', 'Edge', 'Taurus', 'Flex', 'Fiesta', 'Escape', 'GT', 'Ranger'  ],
            'Toyota': ['4Runner', 'Avalon', 'C-HR', 'Camry', '86', 'Corolla', 'Supra', 'Highlander', 'Land Cruiser', 'Mirai', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Yaris', ],
        },
        2019: {
            'BMW': ['2-Series', '3-Series', '4-Series', '5-Series', '7-Series', '8-Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4', 'i3', ],
            'Hyundai': ['Accent', 'Elantra', 'Ioniq', 'Kona', 'Nexo', 'Palisade', 'Santa Fe', 'Sonata', 'Tucson', 'Veloster',],
            'Chrysler': ['300', 'Pacifica', ],
            'Acrua': ['ILX', 'MDX', 'NSX', 'RDX', 'RLX', 'TLX',],
            'Cadillac': ['ATS', 'CT6', 'CTS', 'Escalade', 'XT4', 'XT5', 'XTS',],
            'Honda': ['Accord', 'CR-V', 'Civic', 'Clarity', 'Fit', 'HR-V', 'Insight', 'Odyssey', 'Passport', 'Pilot', 'Ridgeline', ],
            'Jeep': ['Cherokee', 'Compass', 'Grand Cherokee','Renegade', 'Wrangler', 'Wrangler Unlimited'],
            'Mazda': ['CX', 'MX-5', 'Mazda3', 'Mazda6' ],
            'Ram': [ 'ProMaster',  '1500', '2500', '3500'],
            'Dodge': ['Challenger','Charger','Durango','Grand Caravan', 'Journey'],
            'GMC': ['Acadia', 'Canyon', 'Savana', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Mustang',  'Expedition', 'Focus', 'Fusion', 'Edge', 'Taurus', 'Flex', 'Fiesta', 'Escape', 'GT', 'Ranger'  ],
            'Toyota': ['4Runner', 'Avalon', 'C-HR', 'Camry', '86', 'Corolla', 'Supra', 'Highlander', 'Land Cruiser', 'Mirai', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Yaris', ],
        },
        2020: {
            'BMW': ['2-Series', '3-Series', '4-Series', '5-Series', '7-Series', '8-Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4', 'i3', ],
            'Hyundai': ['Accent', 'Elantra', 'Ioniq', 'Kona', 'Nexo', 'Palisade', 'Santa Fe', 'Sonata', 'Tucson', 'Veloster', 'Venue'],
            'Chrysler': ['300', 'Pacifica', 'Voyager'],
            'Acrua': ['ILX', 'MDX', 'NSX', 'RDX', 'RLX', 'TLX',],
            'Cadillac': ['CT4', 'CT5', 'Escalade', 'XT4', 'XT5', 'XT6',],
            'Honda': ['Accord', 'CR-V', 'Civic', 'Clarity', 'Fit', 'HR-V', 'Insight', 'Odyssey', 'Passport', 'Pilot', 'Ridgeline', ],
            'Jeep': ['Cherokee', 'Compass','Gladiator', 'Grand Cherokee','Renegade', 'Wrangler', 'Wrangler Unlimited'],
            'Mazda': ['CX', 'MX-5', 'Mazda3', 'Mazda6' ],
            'Ram': [ 'ProMaster',  '1500', '2500', '3500'],
            'Dodge': ['Challenger','Charger','Durango','Grand Caravan', 'Journey'],
            'GMC': ['Acadia', 'Canyon', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Mustang',  'Expedition', 'Focus', 'Edge',  'Escape', 'Ranger'  ],
            'Toyota': ['4Runner', 'Avalon', 'C-HR', 'Camry', '86', 'Corolla', 'Supra', 'Highlander', 'Land Cruiser', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Yaris', ],
        },
        2021: {
            'BMW': ['2-Series', '3-Series', '4-Series', '5-Series', '7-Series', '8-Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4', 'i3', ],
            'Hyundai': ['Accent', 'Elantra', 'Ioniq', 'Kona', 'Nexo', 'Palisade', 'Santa Cruz', 'Santa Fe', 'Sonata', 'Tucson', 'Veloster', 'Venue'],
            'Chrysler': ['300', 'Pacifica', 'Voyager'],
            'Acrua': ['ILX', 'NSX', 'RDX', 'TLX',],
            'Cadillac': ['CT4', 'CT5', 'Escalade', 'XT4', 'XT5', 'XT6',],
            'Honda': ['Accord', 'CR-V', 'Civic', 'Clarity', 'HR-V', 'Insight', 'Odyssey', 'Passport', 'Pilot', 'Ridgeline', ],
            'Jeep': ['Cherokee', 'Compass','Gladiator', 'Grand Cherokee','Renegade', 'Wrangler', 'Wrangler Unlimited'],
            'Mazda': ['CX', 'MX-5', 'Mazda3', 'Mazda6' ],
            'Ram': [ 'ProMaster',  '1500', '2500', '3500'],
            'Dodge': ['Challenger','Charger','Durango'],
            'GMC': ['Acadia', 'Canyon', 'Hummer', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford' : ['Explorer', 'F-Series', 'Mustang',  'Expedition', 'Focus', 'Edge', 'Escape', 'Ranger', 'Bronco', 'GT', 'Maverick'  ],
            'Toyota': ['4Runner', 'Avalon', 'C-HR', 'Camry', 'GR86', 'Corolla', 'Supra', 'Highlander', 'Land Cruiser',  'Mirai', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Venza', ],
        },
        2022: {
            'BMW': ['2-Series', '3-Series', '4-Series', '5-Series', '7-Series', '8-Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'XM', 'Z4', 'i4', 'iX', ],
            'Hyundai': ['Accent', 'Elantra', 'Ioniq', 'Kona', 'Nexo', 'Palisade', 'Santa Cruz', 'Santa Fe', 'Sonata', 'Tucson', 'Veloster', 'Venue'],
            'Chrysler': ['300', 'Pacifica', 'Voyager'],
            'Acrua': ['ILX', 'MDX', 'NSX', 'RDX', 'TLX',],
            'Cadillac': ['CT4', 'CT5', 'Escalade', 'XT4', 'XT5', 'XT6',],
            'Honda': ['Accord', 'CR-V', 'Civic', 'HR-V', 'Insight', 'Odyssey', 'Passport', 'Pilot', 'Ridgeline', ],
            'Jeep': ['Cherokee', 'Compass','Gladiator', 'Grand Cherokee','Renegade','Wagoneer', 'Wrangler', 'Wrangler Unlimited'],
            'Mazda': ['CX', 'MX-5', 'Mazda3',],
            'Ram': [ 'ProMaster',  '1500', '2500', '3500'],
            'Dodge': ['Challenger','Charger','Durango'],
            'GMC': ['Acadia', 'Canyon', 'Hummer', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Mustang',  'Expedition', 'Focus', 'Edge', 'Escape', 'Ranger', 'Bronco', 'GT', 'Maverick'  ],
            'Toyota': ['4Runner', 'Avalon', 'C-HR', 'Camry', 'GR86', 'Corolla', 'Supra', 'Highlander', 'Mirai', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Venza', ],
        },
        2023: {
            'BMW': ['2-Series', '3-Series', '4-Series', '5-Series', '7-Series', '8-Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'XM', 'Z4', 'i4', 'iX', ],
            'Hyundai': ['Elantra', 'Ioniq', 'Kona', 'Nexo', 'Palisade', 'Santa Cruz', 'Santa Fe', 'Sonata', 'Tucson', 'Venue'],
            'Chrysler': ['300', 'Pacifica'],
            'Acrua': ['Intergra', 'MDX', 'RDX', 'TLX',],
            'Cadillac': ['CT4', 'CT5', 'Escalade', 'Lyriq', 'XT5', 'XT6',],
            'Honda': ['Accord', 'CR-V', 'Civic', 'HR-V', 'Odyssey', 'Passport', 'Pilot', 'Ridgeline', ],
            'Jeep': ['Cherokee', 'Compass','Gladiator', 'Grand Cherokee','Renegade','Wagoneer', 'Wrangler', 'Wrangler Unlimited'],
            'Mazda': ['CX', 'MX-5', 'Mazda3',],
            'Ram': [ 'ProMaster',  '1500', '2500', '3500'],
            'Dodge': ['Challenger','Charger','Durango','Hornet'],
            'GMC': ['Acadia', 'Canyon', 'Hummer', 'Sierra', 'Terrain', 'Yukon', ],
            'Ford': ['Explorer', 'F-Series', 'Mustang',  'Expedition', 'Focus', 'Edge', 'Escape', 'Ranger', 'Bronco', 'GT', 'Maverick'  ],
            'Toyota': ['4Runner', 'Camry', 'Crown', 'GR86', 'Corolla', 'Supra', 'Highlander', 'Mirai', 'Pruis', 'Rav4', 'Sequoia', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Venza', 'bZ4X' ],
        },
       
    };







    // When the year is chosen, then "Make" dropdown shows the listed makes
    yearDropdown.addEventListener('change', function() {
        const selectedYear = this.value;
        const makeDropdown = document.getElementById('make');
        makeDropdown.innerHTML = '<option value="" disabled selected>Select Make</option>';
        for (const make in carData[selectedYear]) {
            const option = document.createElement('option');
            option.value = make;
            option.innerText = make;
            makeDropdown.appendChild(option);
        }
    });

    // When the make changes, update the "Model" dropdown
    document.getElementById('make').addEventListener('change', function() {
        const selectedYear = yearDropdown.value;
        const selectedMake = this.value;
        const modelDropdown = document.getElementById('model');
        modelDropdown.innerHTML = '<option value="" disabled selected>Select Model</option>';
        for (const model of carData[selectedYear][selectedMake]) {
            const option = document.createElement('option');
            option.value = model;
            option.innerText = model;
            modelDropdown.appendChild(option);
        }
    });


